#!/bin/bash
echo "Введите имя файла: "
read filename
$find /home/user/'Рабочий стол'/stankevich_719/ -name '$filename'

if [ -e $filename ];
then
	echo "Выполнено: файл найден"
else
	echo "Ошибка: файла не существует"
        exit 1
fi
echo "Что нужно сделать?
1.Имя файла
2.Тип файла
3.Размер файла
4.Владелец файла
5.Права доступа
6.Дата создания файла
0.Завершить работу"

echo "Введите цифру: "
read var
while [ $var -ne 0 ];
do
echo $var
if [ $var=1 ];
then
	echo "Имя файла: $(basename $filename)";
	read var;
else
	exit 1;
fi

if [ $var==2 ];
then
        echo "Тип файла: $(file -b $filename)";
        read var;
else
        exit 1;
fi

if [ var=3 ];
then
        echo "Размер файла: $(ls -lh $filename | awk '{print $5}')"
        read var
else
        exit 1
fi

if [ var=4 ];
then
        echo "Владелец файла: $(stat -c '%U' $filename)"
        read var
else
        exit 1
fi

if [ var=5 ];
then
        echo "Права доступа: $(stat -c '%A' $filename)"
        read var
else
        exit 1
fi

if [ var=6 ];
then
	 echo "Дата создания файла: $(stat -c '%y' $filename)"
        read var
else
        exit 1
fi;

done
